accent = "#8da1c8"
cursor = "#eff3f8"
foreground = "#eff3f8"
background = "#182538"
selection_foreground = "#eff3f8"
selection_background = "#35445c"

color0 = "#182538"
color1 = "#969293"
color2 = "#61a7d6"
color3 = "#6cabda"
color4 = "#8da1c8"
color5 = "#a0adc5"
color6 = "#5693c4"
color7 = "#b2c5d9"
color8 = "#49586d"
color9 = "#c3c1c1"
color10 = "#a7d0ec"
color11 = "#b3d5ef"
color12 = "#cad4e7"
color13 = "#d8dee9"
color14 = "#97bfdf"
color15 = "#eff3f8"
